a = int(input("number : "))
b = int(input("number : "))

print("Number 1: ", a)
print("Number 2: ", b)
print (a + b)
print (a - b)
print (a * b)
print (a / b)   
print (a % b)
print (a ** b)
print (a // b)
